### ISSUE TITLE
Providing algosearch options

### ISSUE THREAD

**Issue by Kikobeats** [DeuxHuitHuit/algolia-webcrawler#11]
I need provide `attributesToRetrieve` option to algoliasearch client:

https://github.com/algolia/algoliasearch-client-js#parameters-to-control-results-content.

At this point I'm not sure. Could be possible create a config key to pass whatever things to algoliasearchclient?

Like:

```json
{
  "algoliaSearchClient": {
    "attributesToRetrieve": ["url"]
  }
}
```

Could be possible setup `attributesToRetrieve` as configurable option at `config.json`

At this point I'm not sure: Can I provide options to algoliasearch cleitn

**Comment by Kikobeats** [comment]
OK I saw that this is an search options. Strange because I can setup values on the panel. I Thought that could be possible setup it

**Comment by nitriques** [comment]
Please see this part of the readme file: https://github.com/DeuxHuitHuit/algolia-webcrawler#indexsettings-object

index.settings is what you are looking for.
