### ISSUE TITLE
Numeric Values

### ISSUE THREAD

**Issue by kernpunkt-thermann** [DeuxHuitHuit/algolia-webcrawler#16]
In our Config-File we have a field "ranking_value" and "user_interest" that should be interpreted as an numeric value
"selectors": {
		"title": "title",
		"image": "meta[property=\"og:image\"]", 
		"description": "meta[name=\"description\"]",
		"ranking_value":"meta[name=\"as_ranking_value\"]",
		"user_interest":"meta[name=\"as_user_interest\"]",
		"text": "main div.content h1, main div.content h2, main div.content h3, main div.content h4, main div.content h5, main div.content h6, main div.content p, main div.content li, main div.content table",
        "category": ".breadcrumb li:first-child a",
        "breadcrumb": ".breadcrumb li a",
		"product_name": ".product-intro h1",
		"product_intro": ".product-intro h2",
		"interface": ".interface",
		"accessory_developer": ".accessory_developer"
	},
Is there a way to force the crawler to interpret the fields as a number?

Thanks for a quick feedback

Best regards,

Tim

**Comment by kernpunkt-thermann** [comment]
Hi,

we have done following changes: In `config.json`: 
```
"types": {
		"ranking_value": "integer",
		"user_interest": "integer"
	},
```
In process.js we did 
```
if (!!config.types[key]) {				
	// Format all values
	record[key] = _.map(record[key], function (value) {
		switch (config.types[key]) {
			case "integer": {
				return parseInt(value);
			}
			default: return value;
		}					
	});
}
```

**Comment by nitriques** [comment]
That's cool! Wanna send a PR please ?

**Comment by kernpunkt-thermann** [comment]
PR done. #17
