### ISSUE TITLE
Add support for cookies

### ISSUE THREAD

**Issue by RayBB** [DeuxHuitHuit/algolia-webcrawler#30]
Hello,

I was wondering what it would take to support being able to add a cookie.

Basically, I'm trying to do this for Google Sites but I'd need to login first (or give a cookie).

I think requestjs would be good for this but the project doesn't seem to be using this.

Thanks,

**Comment by nitriques** [comment]
You should be able to do it with this https://github.com/DeuxHuitHuit/algolia-webcrawler#http-object

```json
http: {
    headers: {
        cookie: 'blah blah blah'
    }
}
```

Is it not working ?

**Comment by RayBB** [comment]
That did end up working! Thanks for helping

**Comment by nitriques** [comment]
Great! Thanks!
