### ISSUE TITLE
any option to exclude html comments?

### ISSUE THREAD

**Issue by lotsofbytes** [DeuxHuitHuit/algolia-webcrawler#32]
Hi,

First, great program!

I have a question:

The crawler picks up strings inside HTML comments. Is there anyway to prevent it?
For example, I have a following html and <td> is one of selectors. This extracts "main contents begin" and "main contents END".

```
  <td>
    <!--main contents begin --><!--main contents END -->
  </td>
```

Thanks.

**Comment by nitriques** [comment]
Hi ! Thanks!

what css selector are you using ?

**Comment by lotsofbytes** [comment]
Hi,

This is what I have:

```
"selectors": {
		"title": "title",
		"image": "meta[property=\"og:image\"]",
		"description": "meta[name=\"description\"]",
		"text": "h1, h2, h3, h4, h5, h6, p, li, td, div"
	},
```

**Comment by nitriques** [comment]
Yeah I just reproduced the problem in a unit test. Thanks for reporting it !

**Comment by nitriques** [comment]
Can you try this patch 666e5f0 ?

**Comment by lotsofbytes** [comment]
just tried. It works!

thanks.

**Comment by nitriques** [comment]
@lotsofbytes it is now on npm as `2.2.1` Thanks again
