### ISSUE TITLE
setting for user-agent

### ISSUE THREAD

**Issue by lotsofbytes** [DeuxHuitHuit/algolia-webcrawler#33]
I don't see any setting for the User Agent in config.json. Is there any way to set it?

**Comment by nitriques** [comment]
This: https://github.com/DeuxHuitHuit/algolia-webcrawler#http-object
With this: 
```
headers: {
    'User-Agent': 'MY IPHINE 7s'
  }`
```
in it should work. Can you confirm ?

**Comment by lotsofbytes** [comment]
Yes, id did work!

Thanks!

**Comment by nitriques** [comment]
:+1:
