### ISSUE TITLE
Add an option to list entries removed (status at then end)

### ISSUE THREAD

**Issue by lotsofbytes** [DeuxHuitHuit/algolia-webcrawler#34]
I imported 2371 entries but I found only 2003 records in algolia. There was no duplicates or errors when imported. I suspect some entries were removed because they're old? but no way knowing which entry was removed. I wonder if you can add an option to display the url of entries the crawler removes.

I use these setting, so there should not be any deletion.

"oldentries" : 86400000,
 "maxRecordSize": 10000,

**Comment by nitriques** [comment]
Fixed in `2.3.0`, no options needed !

**Comment by lotsofbytes** [comment]
Never mind about the duplicates with query string in my previous post. I found that both entries  are registered in the algolia index.  I will research more.

**Comment by nitriques** [comment]
@lotsofbytes np!

**Comment by nitriques** [comment]
BTW, we've added output at the end with a error summary ;)
