### ISSUE TITLE
hyphen in the title gets removed

### ISSUE THREAD

**Issue by lotsofbytes** [DeuxHuitHuit/algolia-webcrawler#35]
For example,  a html has:

<title>test-test-test-test</title>

This will be stored as 'testtest-test-test' in algolia.

**Comment by nitriques** [comment]
@lotsofbytes Hi! I cannot reproduce. Check 53fa763. The test passes...

**Comment by nitriques** [comment]
@fhamon totally. Maybe we should remove this ?

**Comment by fhamon** [comment]
@nitriques I think we should. Every single website have it's own title separator anyway. 😀

**Comment by nitriques** [comment]
@fhamon see 49a9094f02

**Comment by lotsofbytes** [comment]
thanks!
