### ISSUE TITLE
how to correctly index tags

### ISSUE THREAD

**Issue by Kikobeats** [DeuxHuitHuit/algolia-webcrawler#4]
let a simple example:

url: https://kikobeats.com/reassign-padowan-to-jedi/

ghost header automatically inject tags  as meta tags so is easy select them:

```
$('meta[property=\"article:tag\"]')
```

this selector select this:

```
[<meta property=​"article:​tag" content=​"javascript">​, <meta property=​"article:​tag" content=​"workflow">​, <meta property=​"article:​tag" content=​"programming">​]
```

The problem is that using the current code only the first tag is selected. This posts is indexed in my algolia searh as:

```
tags:
 "javascript"
```

is it possible do a workaround? I understand that tags are a common user case 😄

**Comment by nitriques** [comment]
Yup right now this is unsupported, but it's a great idea. But I think we need a way to only put value in arrays when needed. Any ideas ?

**Comment by nitriques** [comment]
I think that, for each record, we should

1. If its the title node, only process the first record
1. Check all text nodes. If there are values, use them
1. Check the content attribute
1. Check the value attribute

And support multiple values for each key. Only the title and other "private" attributes will remains unchanged. 

Developer willing to get only one value should use the `:eq(0)` selector. Comments ?

**Comment by Kikobeats** [comment]
In fact I don't know why text is an array. Could be all fields arrays?

**Comment by nitriques** [comment]
> In fact I don't know why text is an array.

At the time when I wrote the code, that's the only place I needed multiple values ;)

> Could be all fields arrays?

Yes, I think so! I wanted to prevent the need to deal with arrays in the client side javascript, but thinking about it, I really think I should do what I've propsed yesterday.

**Comment by Kikobeats** [comment]
A good expected behavior could be:

- If the query just have one result then return the first array occurence.
- in other case return the array.

This make easy support title, tags or whatever field 💃
