### ISSUE TITLE
how to correctly setup nested selector

### ISSUE THREAD

**Issue by Kikobeats** [DeuxHuitHuit/algolia-webcrawler#5]
I don't understand why this happens but sometimes nested selectors doesn't work correctly.

I know that maybe this issue is related with a third party used in the code but I need to answer to put in knowledge

### How to reproduce

* url: https://kikobeats.com/reassign-padowan-to-jedi/
* selector: `{"timing": ".post-reading-time span"}` 
* expected: `[<span>​1 min​</span>​]`
* current: `null`

Also I tried to setup another nested selector (`.post-tags a`) that fails. Both selector return an array, I don't know if could be related.

**Comment by nitriques** [comment]
Maybe we need to update cheerio ? Deps are old...

**Comment by nitriques** [comment]
I just figured it out.

Can you replace [this line](https://github.com/DeuxHuitHuit/algolia-webcrawler/blob/master/lib/process.js#L158) with

```js
record[key] = [];
var elements = $(selector);
elements.each(function (index, element) {
    recursiveFind(element, record[key]);
});
```

**Comment by Kikobeats** [comment]
Can I make a PR with this change?

**Comment by nitriques** [comment]
Does it works ? I'd like to fix it in a better way, just wanted to know if the problem was the mentioned line...

**Comment by Kikobeats** [comment]
I have to test it first! 😄 

BTW, is hard read the code. It would be desirable extract independents loop functions into a separate file (like util.js) to make it more easy to be testeable and use the main file just for concat methods.

Also I think that this issue is strongly related with #4.

**Comment by nitriques** [comment]
> BTW, is hard read the code.

I would never say that do anybody that releases open source software. Specially without sending a PR.

This project was setup in under 4 hours and went into production. It easy do understand. It's simple. It gets the job done. Easy to read was never a goal.

I would like to make it better tho. I'd love to have everything you said. But shipping software is always about trade-offs...

**Comment by nitriques** [comment]
Is the code easier to read now ? :P

Both issues should now be fixed.

**Comment by Kikobeats** [comment]
let me check playing with the project this weekend! but thanks for work on it 👍
